version: "3.3"
services:
  backend:
    container_name: "backend"
    build: ./backend
    # logging:
    #   driver: none
    expose:
      - 3000
    ports:
      - 3000:3000
    tty: true

  frontend:
    build: ./frontend
    # logging:
    #   driver: none
    expose:
      - 8000
    ports:
      - 8000:8000

  redis:
    image: redis:latest
    ports:
        - 6379:6379
    volumes:
        - ./config/redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]
  nginx:
    image: nginx:1.13.7
    # logging:
    #   driver: none
    ports:
      - '80:80'
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
